//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Next_View.Properties {
	
	
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("ICSharpCode.SettingsEditor.SettingsCodeGeneratorTool", "5.1.0.5134")]
	internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
		
		private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
		
		public static Settings Default {
			get {
				return defaultInstance;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string Editor {
			get {
				return ((string)(this["Editor"]));
			}
			set {
				this["Editor"] = value;
			}
		}
			
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("en")]
		public string Language {
			get {
				return ((string)(this["Language"]));
			}
			set {
				this["Language"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string LastImage {
			get {
				return ((string)(this["LastImage"]));
			}
			set {
				this["LastImage"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("1")]
		public int LastTab {
			get {
				return ((int)(this["LastTab"]));
			}
			set {
				this["LastTab"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("600")]
		public int MainH {
			get {
				return ((int)(this["MainH"]));
			}
			set {
				this["MainH"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("900")]
		public int MainW {
			get {
				return ((int)(this["MainW"]));
			}
			set {
				this["MainW"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("100")]
		public int MainX {
			get {
				return ((int)(this["MainX"]));
			}
			set {
				this["MainX"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("100")]
		public int MainY {
			get {
				return ((int)(this["MainY"]));
			}
			set {
				this["MainY"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("100")]
		public int Main2X {
			get {
				return ((int)(this["Main2X"]));
			}
			set {
				this["Main2X"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("100")]
		public int Main2Y {
			get {
				return ((int)(this["Main2Y"]));
			}
			set {
				this["Main2Y"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("400")]
		public int SecondH {
			get {
				return ((int)(this["SecondH"]));
			}
			set {
				this["SecondH"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("500")]
		public int SecondW {
			get {
				return ((int)(this["SecondW"]));
			}
			set {
				this["SecondW"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("200")]
		public int SecondX {
			get {
				return ((int)(this["SecondX"]));
			}
			set {
				this["SecondX"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("200")]
		public int SecondY {
			get {
				return ((int)(this["SecondY"]));
			}
			set {
				this["SecondY"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("200")]
		public int Second2X {
			get {
				return ((int)(this["Second2X"]));
			}
			set {
				this["Second2X"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("200")]
		public int Second2Y {
			get {
				return ((int)(this["Second2Y"]));
			}
			set {
				this["Second2Y"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("500")]
		public int ExifH {
			get {
				return ((int)(this["ExifH"]));
			}
			set {
				this["ExifH"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("300")]
		public int ExifW {
			get {
				return ((int)(this["ExifW"]));
			}
			set {
				this["ExifW"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("400")]
		public int ExifX {
			get {
				return ((int)(this["ExifX"]));
			}
			set {
				this["ExifX"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("50")]
		public int ExifY {
			get {
				return ((int)(this["ExifY"]));
			}
			set {
				this["ExifY"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("400")]
		public int Exif2X {
			get {
				return ((int)(this["Exif2X"]));
			}
			set {
				this["Exif2X"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("50")]
		public int Exif2Y {
			get {
				return ((int)(this["Exif2Y"]));
			}
			set {
				this["Exif2Y"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("850")]
		public int DashW {
			get {
				return ((int)(this["DashW"]));
			}
			set {
				this["DashW"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("750")]
		public int DashH {
			get {
				return ((int)(this["DashH"]));
			}
			set {
				this["DashH"] = value;
			}
		}
						
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string RecentImgs {
			get {
				return ((string)(this["RecentImgs"]));
			}
			set {
				this["RecentImgs"] = value;
			}
		}
						
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("True")]
		public bool UpgradeRequired {
			get {
				return ((bool)(this["UpgradeRequired"]));
			}
			set {
				this["UpgradeRequired"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("True")]
		public bool UseMediaDefault {
			get {
				return ((bool)(this["UseMediaDefault"]));
			}
			set {
				this["UseMediaDefault"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("True")]
		public bool HideImg {
			get {
				return ((bool)(this["HideImg"]));
			}
			set {
				this["HideImg"] = value;
			}
		}
				
	}
}
